# Generated by Django 3.2.2 on 2021-07-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
