# Generated by Django 3.2.2 on 2021-07-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210713_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
